/**
 * Sandbox guard sources (SPEC §36). The runner writes these into the isolated
 * working directory: `sitecustomize.py` is imported by every Python process
 * started with the guard directory on `PYTHONPATH`, and `launcher.py` applies
 * the address-space limit before running the analysis code.
 * @module @medresearch/dsh-medical-runner-container/src/guard
 */

/** Modules an analysis may never import; they are the escape surface. */
const BLOCKED_MODULES = [
  'socket',
  'ssl',
  'subprocess',
  'multiprocessing',
  'ctypes',
  'http',
  'urllib',
  'ftplib',
  'smtplib',
  'telnetlib',
  'asyncio',
  'requests',
  'aiohttp',
  'httpx',
] as const

/**
 * Submodules of a blocked package that carry no escape surface. `pathlib`
 * imports `urllib.parse` for pure string parsing, so blocking the whole
 * `urllib` root would make idiomatic generated code (`Path(outdir) / 'x.csv'`)
 * fail without gaining any isolation; `urllib.request` stays blocked.
 */
const ALLOWED_SUBMODULES = ['urllib.parse'] as const

/**
 * Python guard module. Blocks the escape surface at import time and patches
 * the process-spawning entry points that do not require an import.
 * @returns the `sitecustomize.py` source.
 */
export function guardSource(): string {
  const blocked = JSON.stringify(BLOCKED_MODULES)
  const allowed = JSON.stringify(ALLOWED_SUBMODULES)
  return `# Generated by @medresearch/dsh-medical-runner-container. Do not edit.
import builtins
import os

_BLOCKED = set(${blocked})
_ALLOWED = set(${allowed})
_real_import = builtins.__import__


def _guarded_import(name, *args, **kwargs):
    root = name.split('.')[0]
    if root in _BLOCKED and name not in _ALLOWED:
        raise ImportError("module '" + root + "' is blocked by the Med Research runner")
    return _real_import(name, *args, **kwargs)


builtins.__import__ = _guarded_import


def _blocked_process(*args, **kwargs):
    raise PermissionError('process creation is blocked by the Med Research runner')


os.system = _blocked_process
os.popen = _blocked_process
os.execv = _blocked_process
os.execve = _blocked_process
os.spawnv = _blocked_process
os.fork = _blocked_process
`
}

/**
 * Python launcher that applies the memory limit, then runs the analysis file.
 * @returns the `launcher.py` source.
 */
export function launcherSource(): string {
  return `# Generated by @medresearch/dsh-medical-runner-container. Do not edit.
import os
import resource
import runpy
import sys

_limit = int(os.environ['MED_MEMORY_BYTES'])
_address_space = getattr(resource, 'RLIMIT_AS', None)
if _address_space is not None:
    try:
        resource.setrlimit(_address_space, (_limit, _limit))
    except (ValueError, OSError):
        # macOS rejects RLIMIT_AS; the Node-side RSS watchdog enforces the limit.
        pass
_cpu = int(os.environ['MED_CPU_SECONDS'])
_cpu_resource = getattr(resource, 'RLIMIT_CPU', None)
if _cpu_resource is not None:
    try:
        resource.setrlimit(_cpu_resource, (_cpu, _cpu))
    except (ValueError, OSError):
        # Platforms without a usable RLIMIT_CPU still have the Node-side wall-clock limit.
        pass
_target = sys.argv[1]
sys.argv = [_target]
runpy.run_path(_target, run_name='__main__')
`
}
